import type { LayoutConfig, FrameOption, FilterOption, LayoutType } from '../types';

export const LAYOUT_CONFIGS: Record<LayoutType, LayoutConfig> = {
  strip_1x4: {
    id: 'strip_1x4',
    name: 'Classic Strip 1×4',
    subtitle: 'Signature 4-cut vertical studio strip',
    photoCount: 4,
    columns: 1,
    rows: 4,
    aspectRatio: '1:3.2',
  },
  strip_1x3: {
    id: 'strip_1x3',
    name: 'Trio Strip 1×3',
    subtitle: 'Editorial 3-cut vertical portrait',
    photoCount: 3,
    columns: 1,
    rows: 3,
    aspectRatio: '1:2.4',
  },
  grid_2x2: {
    id: 'grid_2x2',
    name: 'Studio Grid 2×2',
    subtitle: 'Modern square quad collage',
    photoCount: 4,
    columns: 2,
    rows: 2,
    aspectRatio: '1:1.15',
  },
  grid_3x3: {
    id: 'grid_3x3',
    name: 'Mega Collage 3×3',
    subtitle: 'Iconic 9-cut Korean mega photostrip',
    photoCount: 9,
    columns: 3,
    rows: 3,
    aspectRatio: '1:1.15',
  },
  grid_2x3: {
    id: 'grid_2x3',
    name: 'Portrait Grid 2×3',
    subtitle: 'Editorial 6-cut story collage',
    photoCount: 6,
    columns: 2,
    rows: 3,
    aspectRatio: '1:1.6',
  },
  strip_1x2: {
    id: 'strip_1x2',
    name: 'Duo Strip 1×2',
    subtitle: 'Minimal 2-cut quick strip',
    photoCount: 2,
    columns: 1,
    rows: 2,
    aspectRatio: '1:1.7',
  },
  polaroid_1x1: {
    id: 'polaroid_1x1',
    name: 'Solo Polaroid 1×1',
    subtitle: 'Iconic single portrait with bottom stamp',
    photoCount: 1,
    columns: 1,
    rows: 1,
    aspectRatio: '1:1.2',
  },
};

/**
 * Returns the layout configuration that best fits the exact number of photos taken
 */
export function getFittingLayout(photoCount: number): LayoutType {
  if (photoCount <= 1) return 'polaroid_1x1';
  if (photoCount === 2) return 'strip_1x2';
  if (photoCount === 3) return 'strip_1x3';
  if (photoCount === 4 || photoCount === 5) return 'strip_1x4';
  if (photoCount >= 6 && photoCount < 9) return 'grid_2x3';
  return 'grid_3x3';
}

export const FRAME_OPTIONS: FrameOption[] = [
  // --- Category 1: Minimalist Solid ---
  {
    id: 'cloud_white',
    name: 'Cloud White',
    category: 'solid',
    color: '#FFFFFF',
    textColor: '#1A1A1A',
    subtextColor: '#737373',
    borderColor: 'rgba(0, 0, 0, 0.15)',
    borderPreviewClass: 'bg-white border border-stone-300',
    tagline: 'Clean minimal studio white',
  },
  {
    id: 'matte_charcoal',
    name: 'Matte Charcoal',
    category: 'solid',
    color: '#1F1F1F',
    textColor: '#FBFBFA',
    subtextColor: '#999999',
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderPreviewClass: 'bg-[#1F1F1F] border border-neutral-700 text-white',
    tagline: 'Noir darkroom contrast',
  },
  {
    id: 'oat_cream',
    name: 'Oat Cream',
    category: 'solid',
    color: '#F5F3ED',
    textColor: '#2E2B27',
    subtextColor: '#7A756D',
    borderColor: 'rgba(180, 170, 155, 0.4)',
    borderPreviewClass: 'bg-[#F5F3ED] border border-[#E3DFCE] text-stone-800',
    tagline: 'Warm organic textured paper',
  },
  {
    id: 'blush_pink',
    name: 'Blush Pink',
    category: 'solid',
    color: '#FCEEE9',
    textColor: '#422F2A',
    subtextColor: '#8C746F',
    borderColor: 'rgba(230, 190, 180, 0.5)',
    borderPreviewClass: 'bg-[#FCEEE9] border border-[#F4DDD5] text-stone-800',
    tagline: 'Soft studio pastel rose',
  },
  {
    id: 'butter_milk',
    name: 'Butter Milk',
    category: 'solid',
    color: '#FFF8E7',
    textColor: '#4A4228',
    subtextColor: '#8C8059',
    borderColor: 'rgba(230, 215, 170, 0.6)',
    borderPreviewClass: 'bg-[#FFF8E7] border border-[#EDE0B8] text-stone-800',
    tagline: 'Warm sunny pastry cream',
  },
  {
    id: 'sage_green',
    name: 'Sage Green',
    category: 'solid',
    color: '#EAF0E8',
    textColor: '#2D3A2C',
    subtextColor: '#697B67',
    borderColor: 'rgba(175, 195, 170, 0.5)',
    borderPreviewClass: 'bg-[#EAF0E8] border border-[#D0DDD0] text-stone-800',
    tagline: 'Peaceful earthy matcha tint',
  },
  {
    id: 'sky_mist',
    name: 'Sky Mist',
    category: 'solid',
    color: '#EAF2F8',
    textColor: '#1E3345',
    subtextColor: '#5C7991',
    borderColor: 'rgba(170, 195, 220, 0.5)',
    borderPreviewClass: 'bg-[#EAF2F8] border border-[#CCE0EE] text-stone-800',
    tagline: 'Gentle morning breeze blue',
  },
  {
    id: 'lavender_milk',
    name: 'Lavender Milk',
    category: 'solid',
    color: '#F2EEF9',
    textColor: '#36284B',
    subtextColor: '#766491',
    borderColor: 'rgba(205, 190, 225, 0.5)',
    borderPreviewClass: 'bg-[#F2EEF9] border border-[#DCD3EB] text-stone-800',
    tagline: 'Soft whimsical lilac haze',
  },
  {
    id: 'cocoa_muted',
    name: 'Cocoa Muted',
    category: 'solid',
    color: '#3B3332',
    textColor: '#F5ECE8',
    subtextColor: '#B8A8A5',
    borderColor: 'rgba(255, 255, 255, 0.18)',
    borderPreviewClass: 'bg-[#3B3332] border border-[#524745] text-stone-100',
    tagline: 'Deep rich espresso warmth',
  },
  {
    id: 'midnight_navy',
    name: 'Midnight Navy',
    category: 'solid',
    color: '#0F172A',
    textColor: '#F8FAFC',
    subtextColor: '#94A3B8',
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderPreviewClass: 'bg-[#0F172A] border border-slate-700 text-slate-100',
    tagline: 'Deep Korean twilight with crisp silver typography',
  },
  {
    id: 'matcha_latte',
    name: 'Matcha Cream',
    category: 'solid',
    color: '#E8EFE6',
    textColor: '#283626',
    subtextColor: '#60725D',
    borderColor: 'rgba(160, 185, 155, 0.5)',
    borderPreviewClass: 'bg-[#E8EFE6] border border-[#CCD8C8] text-stone-800',
    tagline: 'Soothing organic green tea with creamy undertone',
  },
  {
    id: 'sunset_apricot',
    name: 'Sunset Apricot',
    category: 'solid',
    color: '#FEEFE8',
    textColor: '#5A2D22',
    subtextColor: '#9E6455',
    borderColor: 'rgba(240, 195, 180, 0.5)',
    borderPreviewClass: 'bg-[#FEEFE8] border border-[#F8D2C4] text-stone-800',
    tagline: 'Warm golden peachy glow of golden hour',
  },
  {
    id: 'wine_bordeaux',
    name: 'Deep Bordeaux',
    category: 'solid',
    color: '#38161D',
    textColor: '#FAF0F2',
    subtextColor: '#B58893',
    borderColor: 'rgba(255, 255, 255, 0.18)',
    borderPreviewClass: 'bg-[#38161D] border border-[#54252F] text-rose-100',
    tagline: 'Luxurious velvet dark cherry wine paper',
  },

  // --- Category 2: Retro Vintage ---
  {
    id: 'retro_film',
    name: '35mm Film Roll',
    category: 'retro',
    emoji: '🎞️',
    color: '#241E19',
    textColor: '#F5ECE3',
    subtextColor: '#C7B9A9',
    borderColor: '#3D342C',
    borderPreviewClass: 'bg-[#241E19] border border-[#4D4036] text-amber-100',
    tagline: 'Analog negative with sprocket holes & ISO stamps',
  },
  {
    id: 'retro_newspaper',
    name: 'The Daily Chronicle',
    category: 'retro',
    emoji: '📰',
    color: '#F4EFE6',
    textColor: '#1E1B18',
    subtextColor: '#69625A',
    borderColor: '#3A342D',
    borderPreviewClass: 'bg-[#F4EFE6] border-2 border-[#2E2822] text-stone-900',
    tagline: 'Vintage editorial with ornate pinstripes',
  },
  {
    id: 'retro_vhs',
    name: 'Cyber VHS 1998',
    category: 'retro',
    emoji: '📼',
    color: '#131826',
    textColor: '#57E2F7',
    subtextColor: '#F472B6',
    borderColor: '#38BDF8',
    borderPreviewClass: 'bg-[#131826] border border-cyan-500/50 text-cyan-300',
    tagline: '90s camcorder tracking lines & neon glow',
  },
  {
    id: 'retro_polaroid',
    name: 'Classic Polaroid 600',
    category: 'retro',
    emoji: '📷',
    color: '#FAF7F0',
    textColor: '#292524',
    subtextColor: '#78716C',
    borderColor: '#E7E2D6',
    borderPreviewClass: 'bg-[#FAF7F0] border-2 border-[#DCD5C5] text-stone-900',
    tagline: 'Vintage instant camera card with handwritten vibe',
  },
  {
    id: 'retro_airmail',
    name: 'Vintage Airmail',
    category: 'retro',
    emoji: '✉️',
    color: '#F9F5EC',
    textColor: '#1E293B',
    subtextColor: '#64748B',
    borderColor: '#E2D9C8',
    borderPreviewClass: 'bg-[#F9F5EC] border border-[#D5C9B3] text-stone-900',
    tagline: 'Nostalgic blue & red striped postal border',
  },
  {
    id: 'retro_cassette',
    name: 'Cassette Mixtape 1984',
    category: 'retro',
    emoji: '📼',
    color: '#262220',
    textColor: '#F4ECE4',
    subtextColor: '#D4A373',
    borderColor: '#423A35',
    borderPreviewClass: 'bg-[#262220] border border-[#52463F] text-amber-200',
    tagline: 'Vintage analog cassette tape with reel markers & side labels',
  },
  {
    id: 'retro_ticket',
    name: 'Cinema Ticket Stub',
    category: 'retro',
    emoji: '🎟️',
    color: '#F6F1E7',
    textColor: '#292524',
    subtextColor: '#78716C',
    borderColor: '#3F3935',
    borderPreviewClass: 'bg-[#F6F1E7] border-2 border-dashed border-[#574E47] text-stone-900',
    tagline: 'Vintage theater admission voucher with punched star stamps',
  },

  // --- Category 3: Cute & Kawaii ---
  {
    id: 'cute_cherry',
    name: 'Sweet Cherry Hearts',
    category: 'cute',
    emoji: '🍒',
    color: '#FFF0F3',
    textColor: '#9E2A2B',
    subtextColor: '#C96868',
    borderColor: '#F8B4B4',
    borderPreviewClass: 'bg-[#FFF0F3] border border-pink-300 text-pink-900',
    tagline: 'Pastel pink with cute cherries & mini hearts',
  },
  {
    id: 'cute_daisy',
    name: 'Sunny Daisy',
    category: 'cute',
    emoji: '🌼',
    color: '#FFFEEA',
    textColor: '#585123',
    subtextColor: '#857C3E',
    borderColor: '#F6E05E',
    borderPreviewClass: 'bg-[#FFFEEA] border border-amber-300 text-amber-900',
    tagline: 'Happy daisies with cheerful blossoms & doodles',
  },
  {
    id: 'cute_cloud',
    name: 'Dreamy Cloud Sky',
    category: 'cute',
    emoji: '☁️',
    color: '#F0F6FF',
    textColor: '#1E40AF',
    subtextColor: '#60A5FA',
    borderColor: '#BFDBFE',
    borderPreviewClass: 'bg-gradient-to-b from-[#EFF6FF] to-[#FAF5FF] border border-blue-200 text-blue-900',
    tagline: 'Fluffy clouds with sparkling stars',
  },
  {
    id: 'cute_cat',
    name: 'Kitty Paws',
    category: 'cute',
    emoji: '🐾',
    color: '#FAF6F0',
    textColor: '#3D342A',
    subtextColor: '#A08F7E',
    borderColor: '#E8DED1',
    borderPreviewClass: 'bg-[#FAF6F0] border border-stone-300 text-stone-800',
    tagline: 'Kawaii cat ears, whiskers & climbing paw prints',
  },
  {
    id: 'cute_bunny',
    name: 'Bunny Hop',
    category: 'cute',
    emoji: '🐰',
    color: '#FDF2F8',
    textColor: '#831843',
    subtextColor: '#DB2777',
    borderColor: '#FBCFE8',
    borderPreviewClass: 'bg-[#FDF2F8] border border-pink-200 text-pink-950',
    tagline: 'Adorably soft bunny ears & ribbon bows',
  },
  {
    id: 'cute_strawberry',
    name: 'Strawberries & Cream',
    category: 'cute',
    emoji: '🍓',
    color: '#FFF1F2',
    textColor: '#9F1239',
    subtextColor: '#E11D48',
    borderColor: '#FECDD3',
    borderPreviewClass: 'bg-[#FFF1F2] border border-rose-200 text-rose-950',
    tagline: 'Fresh juicy berries & sweet milk splashes',
  },
  {
    id: 'cute_bear',
    name: 'Teddy Honey Bear',
    category: 'cute',
    emoji: '🧸',
    color: '#FAF4EC',
    textColor: '#4A3728',
    subtextColor: '#8C6F55',
    borderColor: '#E6D7C3',
    borderPreviewClass: 'bg-[#FAF4EC] border border-[#E0CFBA] text-amber-950',
    tagline: 'Sweet brown honey bear ears and playful honey jars',
  },
  {
    id: 'cute_heart_ribbon',
    name: 'Coquette Bow Ribbon',
    category: 'cute',
    emoji: '🎀',
    color: '#FFF5F8',
    textColor: '#881337',
    subtextColor: '#E11D48',
    borderColor: '#FBCFE8',
    borderPreviewClass: 'bg-[#FFF5F8] border border-pink-300 text-pink-900',
    tagline: 'Trendy Korean coquette aesthetic with tied ribbons & glitter hearts',
  },
  {
    id: 'cute_dino',
    name: 'Baby Dino Garden',
    category: 'cute',
    emoji: '🦖',
    color: '#F0F9F4',
    textColor: '#14532D',
    subtextColor: '#22C55E',
    borderColor: '#BBF7D0',
    borderPreviewClass: 'bg-[#F0F9F4] border border-emerald-200 text-emerald-950',
    tagline: 'Cute friendly baby dinos and pastel stars',
  },

  // --- Category 4: Y2K & Cyber ---
  {
    id: 'y2k_holo',
    name: 'Cyber Holo Chrome',
    category: 'y2k',
    emoji: '💿',
    color: '#10121A',
    textColor: '#E0E7FF',
    subtextColor: '#818CF8',
    borderColor: '#6366F1',
    borderPreviewClass: 'bg-[#10121A] border border-indigo-500 text-indigo-200',
    tagline: 'Holographic metallic gradient & cyber cross stars',
  },
  {
    id: 'y2k_pixel',
    name: 'Digital Pixel Star',
    category: 'y2k',
    emoji: '👾',
    color: '#18122B',
    textColor: '#E9D5FF',
    subtextColor: '#A855F7',
    borderColor: '#7E22CE',
    borderPreviewClass: 'bg-[#18122B] border border-purple-500 text-purple-200',
    tagline: 'Retro 8-bit pixel sparkles & arcade nostalgia',
  },
  {
    id: 'y2k_bubblegum',
    name: 'Bubblegum Pop',
    category: 'y2k',
    emoji: '💖',
    color: '#FFE4E6',
    textColor: '#881337',
    subtextColor: '#BE123C',
    borderColor: '#FDA4AF',
    borderPreviewClass: 'bg-[#FFE4E6] border border-rose-300 text-rose-900',
    tagline: 'Early 2000s glossy sticker bomb aesthetic',
  },
  {
    id: 'y2k_cyberpunk',
    name: 'Neon Matrix Grid',
    category: 'y2k',
    emoji: '⚡',
    color: '#0A0E17',
    textColor: '#4ADE80',
    subtextColor: '#22D3EE',
    borderColor: '#22C55E',
    borderPreviewClass: 'bg-[#0A0E17] border border-green-500 text-green-300',
    tagline: 'Cyber green terminal scanlines & futuristic matrix lines',
  },
  {
    id: 'y2k_glitter_star',
    name: 'Silver Starburst',
    category: 'y2k',
    emoji: '⭐',
    color: '#151722',
    textColor: '#F1F5F9',
    subtextColor: '#94A3B8',
    borderColor: '#CBD5E1',
    borderPreviewClass: 'bg-[#151722] border border-slate-400 text-slate-100',
    tagline: 'Metallic 4-point chrome starbursts with diamond sparkles',
  },
];

export const FILTER_OPTIONS: FilterOption[] = [
  {
    id: 'normal',
    name: 'Natural Glow',
    koreanName: '자연스러운',
    description: 'Clean balanced studio lighting with soft warmth',
  },
  {
    id: 'bw',
    name: 'Noir Editorial',
    koreanName: '흑백 필름',
    description: 'Timeless high-contrast black & white aesthetic',
  },
  {
    id: 'sepia',
    name: 'Tokyo Warmth',
    koreanName: '빈티지 웜',
    description: 'Nostalgic golden-hour tones with gentle warmth',
  },
  {
    id: 'grain',
    name: 'Silver Grain',
    koreanName: '필름 그레인',
    description: 'Analog 35mm film texture with cinematic grain',
  },
  {
    id: 'pastel',
    name: 'Pastel Dream',
    koreanName: '파스텔 핑크',
    description: 'Soft dreamy pastel tones with lifted shadows',
  },
  {
    id: 'fuji',
    name: 'Fuji Astia',
    koreanName: '후지 필름',
    description: 'Vibrant greens, crisp cool skies & true Japanese film colors',
  },
  {
    id: 'cyber',
    name: 'Y2K Cyber',
    koreanName: '사이버 네온',
    description: 'Electric cool tones & high-energy cyberpunk contrast',
  },
  {
    id: 'cinema',
    name: 'Moody Teal',
    koreanName: '시네마틱',
    description: 'Cinematic teal undertones with warm golden skin highlights',
  },
  {
    id: 'soft',
    name: 'Milk Soft',
    koreanName: '밀크 소프트',
    description: 'Gentle bloom lighting with creamy Korean skin finish',
  },
  {
    id: 'kodak',
    name: 'Kodak Gold 200',
    koreanName: '코닥 골드',
    description: 'Golden-hour daylight tones with rich, nostalgic warmth',
  },
  {
    id: 'moody_noir',
    name: 'Deep Silver Noir',
    koreanName: '딥 느와르',
    description: 'Dramatic editorial monochrome with velvety deep blacks',
  },
  {
    id: 'haru_blue',
    name: 'Haru Film Cool',
    koreanName: '하루 블루',
    description: 'Signature clean bright skin finish with crisp cool blue undertones',
  },
  {
    id: 'cherry_blossom',
    name: 'Cherry Blossom',
    koreanName: '벚꽃 블러셔',
    description: 'Soft rosy cheek glow with dreamy romantic blossom highlights',
  },
  {
    id: 'warm_latte',
    name: 'Oat Milk Latte',
    koreanName: '오트 라떼',
    description: 'Cozy café cream tones with muted contrast and warm latte textures',
  },
  {
    id: 'vintage_90s',
    name: '90s Disposable',
    koreanName: '일회용 카메라',
    description: 'Punchy flash camera nostalgia with authentic 90s film saturation',
  },
];
