import type { LayoutConfig, FrameOption, FilterOption, LayoutType } from '../types';

export const LAYOUT_CONFIGS: Record<LayoutType, LayoutConfig> = {
  strip_1x4: {
    id: 'strip_1x4',
    name: 'Classic Strip 1×4',
    subtitle: 'Signature 4-cut vertical studio strip',
    photoCount: 4,
    columns: 1,
    rows: 4,
    aspectRatio: '1:3.2',
  },
  strip_1x3: {
    id: 'strip_1x3',
    name: 'Trio Strip 1×3',
    subtitle: 'Editorial 3-cut vertical portrait',
    photoCount: 3,
    columns: 1,
    rows: 3,
    aspectRatio: '1:2.4',
  },
  grid_2x2: {
    id: 'grid_2x2',
    name: 'Studio Grid 2×2',
    subtitle: 'Modern square quad collage',
    photoCount: 4,
    columns: 2,
    rows: 2,
    aspectRatio: '1:1.15',
  },
  strip_1x2: {
    id: 'strip_1x2',
    name: 'Duo Strip 1×2',
    subtitle: 'Minimal 2-cut quick polaroid',
    photoCount: 2,
    columns: 1,
    rows: 2,
    aspectRatio: '1:1.7',
  },
};

export const FRAME_OPTIONS: FrameOption[] = [
  // --- Category 1: Minimalist Solid ---
  {
    id: 'cloud_white',
    name: 'Cloud White',
    category: 'solid',
    color: '#FFFFFF',
    textColor: '#1A1A1A',
    subtextColor: '#737373',
    borderColor: 'rgba(0, 0, 0, 0.15)',
    borderPreviewClass: 'bg-white border border-stone-300',
    tagline: 'Clean minimal studio white',
  },
  {
    id: 'matte_charcoal',
    name: 'Matte Charcoal',
    category: 'solid',
    color: '#1F1F1F',
    textColor: '#FBFBFA',
    subtextColor: '#999999',
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderPreviewClass: 'bg-[#1F1F1F] border border-neutral-700 text-white',
    tagline: 'Noir darkroom contrast',
  },
  {
    id: 'oat_cream',
    name: 'Oat Cream',
    category: 'solid',
    color: '#F5F3ED',
    textColor: '#2E2B27',
    subtextColor: '#7A756D',
    borderColor: 'rgba(180, 170, 155, 0.4)',
    borderPreviewClass: 'bg-[#F5F3ED] border border-[#E3DFCE] text-stone-800',
    tagline: 'Warm organic textured paper',
  },
  {
    id: 'blush_pink',
    name: 'Blush Pink',
    category: 'solid',
    color: '#FCEEE9',
    textColor: '#422F2A',
    subtextColor: '#8C746F',
    borderColor: 'rgba(230, 190, 180, 0.5)',
    borderPreviewClass: 'bg-[#FCEEE9] border border-[#F4DDD5] text-stone-800',
    tagline: 'Soft studio pastel rose',
  },

  // --- Category 2: Retro Vintage ---
  {
    id: 'retro_film',
    name: '35mm Film Roll',
    category: 'retro',
    emoji: '🎞️',
    color: '#241E19',
    textColor: '#F5ECE3',
    subtextColor: '#C7B9A9',
    borderColor: '#3D342C',
    borderPreviewClass: 'bg-[#241E19] border border-[#4D4036] text-amber-100',
    tagline: 'Analog negative with sprocket holes & ISO stamps',
  },
  {
    id: 'retro_newspaper',
    name: 'The Daily Chronicle',
    category: 'retro',
    emoji: '📰',
    color: '#F4EFE6',
    textColor: '#1E1B18',
    subtextColor: '#69625A',
    borderColor: '#3A342D',
    borderPreviewClass: 'bg-[#F4EFE6] border-2 border-[#2E2822] text-stone-900',
    tagline: 'Vintage editorial with ornate pinstripes',
  },
  {
    id: 'retro_vhs',
    name: 'Cyber VHS 1998',
    category: 'retro',
    emoji: '📼',
    color: '#131826',
    textColor: '#57E2F7',
    subtextColor: '#F472B6',
    borderColor: '#38BDF8',
    isPro: true,
    borderPreviewClass: 'bg-[#131826] border border-cyan-500/50 text-cyan-300',
    tagline: '90s camcorder tracking lines & neon glow',
  },

  // --- Category 3: Cute & Kawaii ---
  {
    id: 'cute_cherry',
    name: 'Sweet Cherry Hearts',
    category: 'cute',
    emoji: '🍒',
    color: '#FFF0F3',
    textColor: '#9E2A2B',
    subtextColor: '#C96868',
    borderColor: '#F8B4B4',
    borderPreviewClass: 'bg-[#FFF0F3] border border-pink-300 text-pink-900',
    tagline: 'Pastel pink with cute cherries & mini hearts',
  },
  {
    id: 'cute_daisy',
    name: 'Sunny Daisy',
    category: 'cute',
    emoji: '🌼',
    color: '#FFFEEA',
    textColor: '#585123',
    subtextColor: '#857C3E',
    borderColor: '#F6E05E',
    borderPreviewClass: 'bg-[#FFFEEA] border border-amber-300 text-amber-900',
    tagline: 'Happy daisies with cheerful blossoms & doodles',
  },
  {
    id: 'cute_cloud',
    name: 'Dreamy Cloud Sky',
    category: 'cute',
    emoji: '☁️',
    color: '#F0F6FF',
    textColor: '#1E40AF',
    subtextColor: '#60A5FA',
    borderColor: '#BFDBFE',
    borderPreviewClass: 'bg-gradient-to-b from-[#EFF6FF] to-[#FAF5FF] border border-blue-200 text-blue-900',
    tagline: 'Fluffy clouds with sparkling stars',
  },
  {
    id: 'cute_cat',
    name: 'Kitty Paws',
    category: 'cute',
    emoji: '🐾',
    color: '#FAF6F0',
    textColor: '#3D342A',
    subtextColor: '#A08F7E',
    borderColor: '#E8DED1',
    isPro: true,
    borderPreviewClass: 'bg-[#FAF6F0] border border-stone-300 text-stone-800',
    tagline: 'Kawaii cat ears, whiskers & climbing paw prints',
  },
];

export const FILTER_OPTIONS: FilterOption[] = [
  {
    id: 'normal',
    name: 'Natural Glow',
    koreanName: '자연스러운',
    description: 'Clean balanced studio lighting with soft warmth',
  },
  {
    id: 'bw',
    name: 'Noir Editorial',
    koreanName: '흑백 필름',
    description: 'Timeless high-contrast black & white aesthetic',
  },
  {
    id: 'sepia',
    name: 'Tokyo Warmth',
    koreanName: '빈티지 웜',
    description: 'Nostalgic golden-hour tones with gentle warmth',
  },
  {
    id: 'grain',
    name: 'Silver Grain',
    koreanName: '필름 그레인',
    description: 'Analog 35mm film texture with cinematic grain',
  },
];
